### ISSUE TITLE
[Bug] Action error: Error: undefined not constructable

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/steam#144]
I updated my wagon to latest:
`gem 'locomotivecms_steam', git: 'https://github.com/locomotivecms/steam', ref: '742fb92'`

After updating all my actions started failing.
I did some research and found out that its crashing because of this line:
`const logger = new Duktape.Logger();`

After doing some digging I found this: https://github.com/svaarala/duktape/blob/master/doc/logging.rst
According to the description, in 2.x versions of Duktape, logger is an extra that needs to be included.
I believe the logger feature is extremely useful and makes the process of debugging way faster and easier. Can we include the logging extra?

Getting the following error:
```
#<Locomotive::Steam::ActionError: undefined not constructable>
  Error: undefined not constructable
  /Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/services/action_service.rb:46:in `call_prop'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/services/action_service.rb:46:in `run'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/liquid/tags/action.rb:42:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:215:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:269:in `with_profiling'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:214:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/liquid/template.rb:16:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/renderer.rb:47:in `parse_and_render_liquid'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/renderer.rb:23:in `render_page'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/renderer.rb:11:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/path.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/impersonated_entry.rb:40:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/redirection.rb:15:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/locale.rb:29:in `block in _call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/locale.rb:28:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/robots.rb:13:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/default_env.rb:17:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/lint.rb:49:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/lint.rb:37:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_wagon-3.0.0.rc0/lib/locomotive/wagon/middlewares/error_page.rb:16:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/dragonfly-1.2.0/lib/dragonfly/middleware.rb:14:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/dynamic_assets.rb:22:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/static.rb:149:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/bundler/gems/steam-742fb927b6dd/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

**Comment by did** [comment]
https://github.com/judofyr/duktape.rb/issues/44

**Comment by did** [comment]
@DonKoko, instead of using `new Duktape.Logger()`, now, you've got `log("my message")` instead. It should be even simpler :-)

**Comment by DonKoko** [comment]
@did just saw your commit. That is amazing. I can how update my steam :)
