### ISSUE TITLE
[Bug] Calling any? on a collection gives error

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/steam#153]
Any of those 2 expressions will cause the rendering to crash. I also tried it in an if case and same thing happened. 
```liquid
    {{activity.activity_slides}}
    {{contents.activity_slides.any?}}
```

Issue happens only when there is a `has_many` relationship. With `many_to_many` it works fine.

Error:
```
no implicit conversion of nil into Hash

No code
Backtrace (click here to display it)

/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:21:in `merge'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:21:in `block (2 levels) in load_list'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:107:in `block in each'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:101:in `each'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:101:in `each'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:20:in `block in load_list'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:19:in `tap'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:19:in `load_list'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/yaml_loaders/content_entry.rb:13:in `load'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:114:in `collection'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:102:in `block in populate_dataset'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/sanitizer.rb:20:in `with'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:101:in `populate_dataset'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:96:in `block in dataset'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:95:in `tap'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:95:in `dataset'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:86:in `block in memoized_dataset'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem/simple_cache_store.rb:11:in `fetch'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:85:in `memoized_dataset'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:27:in `all'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:81:in `_query'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/adapters/filesystem.rb:31:in `query'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/models/repository.rb:52:in `query'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/repositories/content_entry_repository.rb:47:in `all'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/liquid/drops/content_entry_collection.rb:59:in `collection'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/liquid/drops/content_entry_collection.rb:8:in `any?'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/drop.rb:37:in `invoke_drop'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:197:in `lookup_and_evaluate'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/variable_lookup.rb:46:in `block in evaluate'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/variable_lookup.rb:36:in `each_index'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/variable_lookup.rb:36:in `evaluate'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:164:in `evaluate'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/variable.rb:78:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:71:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:64:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/liquid/tags/inherited_block.rb:42:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/liquid/tags/extends.rb:10:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/liquid/tags/extends.rb:8:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:215:in `block in render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:269:in `with_profiling'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:214:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/liquid/template.rb:16:in `render'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/renderer.rb:42:in `parse_and_render_liquid'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/renderer.rb:23:in `render_page'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/renderer.rb:11:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/path.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/impersonated_entry.rb:36:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/redirection.rb:15:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/locale.rb:29:in `block in _call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/locale.rb:28:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/robots.rb:13:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/default_env.rb:17:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/lint.rb:49:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/lint.rb:37:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_wagon-3.0.0.rc0/lib/locomotive/wagon/middlewares/error_page.rb:16:in `_call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/dragonfly-1.2.0/lib/dragonfly/middleware.rb:14:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/dynamic_assets.rb:22:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/static.rb:149:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_steam-1.5.0.rc0/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'
/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool'
```

**Comment by DonKoko** [comment]
Issue was happening because the yml data was the default data when generating a content_type and that was not corresponding to the content_type definition. I assume thats what happened. Once i removed those entries from the data file, the issue was solved.
