### ISSUE TITLE
Duktape::TypeError invalid base value

### ISSUE THREAD

**Issue by loyaruarutoitsu** [locomotivecms/steam#79]
The trace:
```
locomotivecms_steam (1.2.0) lib/locomotive/steam/services/action_service.rb:42:in `call_prop'
locomotivecms_steam (1.2.0) lib/locomotive/steam/services/action_service.rb:42:in `run'
locomotivecms_steam (1.2.0) lib/locomotive/steam/liquid/tags/action.rb:41:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/tags/inherited_block.rb:71:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
locomotivecms-liquid (4.0.0) lib/liquid/tags/inherited_block.rb:64:in `render'
locomotivecms_steam (1.2.0) lib/locomotive/steam/liquid/tags/inherited_block.rb:42:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
locomotivecms_steam (1.2.0) lib/locomotive/steam/liquid/tags/extends.rb:10:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
locomotivecms_steam (1.2.0) lib/locomotive/steam/liquid/tags/extends.rb:8:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/block.rb:15:in `render'
locomotivecms_steam (1.2.0) lib/locomotive/steam/liquid/tags/extends.rb:10:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/context.rb:128:in `stack'
locomotivecms_steam (1.2.0) lib/locomotive/steam/liquid/tags/extends.rb:8:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:105:in `render_token'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:87:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `each'
locomotivecms-liquid (4.0.0) lib/liquid/block_body.rb:74:in `render'
locomotivecms-liquid (4.0.0) lib/liquid/template.rb:215:in `block in render'
locomotivecms-liquid (4.0.0) lib/liquid/template.rb:269:in `with_profiling'
locomotivecms-liquid (4.0.0) lib/liquid/template.rb:214:in `render'
locomotivecms_steam (1.2.0) lib/locomotive/steam/liquid/template.rb:17:in `render'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/renderer.rb:40:in `parse_and_render_liquid'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms (3.2.0) lib/locomotive/steam/middlewares/cache.rb:19:in `call'
locomotivecms (3.2.0) lib/locomotive/steam/middlewares/page_editing.rb:16:in `call'
locomotivecms (3.2.0) lib/locomotive/steam/middlewares/missing_translations.rb:13:in `block in call'
locomotivecms (3.2.0) lib/locomotive/steam/middlewares/missing_translations.rb:24:in `find_and_persist_missing_translations'
locomotivecms (3.2.0) lib/locomotive/steam/middlewares/missing_translations.rb:12:in `call'
locomotivecms (3.2.0) lib/locomotive/steam/middlewares/wysihtml_css.rb:12:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/path.rb:13:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
i18n (0.7.0) lib/i18n.rb:257:in `with_locale'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
activesupport (4.2.6) lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/robots.rb:15:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/logging.rb:18:in `call'
locomotivecms (3.2.0) lib/locomotive/steam/middlewares/catch_error.rb:13:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
locomotivecms_steam (1.2.0) lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
rack (1.6.5) lib/rack/builder.rb:153:in `call'
actionpack (4.2.6) lib/action_dispatch/routing/mapper.rb:51:in `serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
locomotivecms (3.2.0) lib/locomotive/middlewares/site.rb:26:in `call'
dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (1.6.5) lib/rack/etag.rb:24:in `call'
rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.5) lib/rack/head.rb:13:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.5) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
locomotivecms (3.2.0) lib/locomotive/middlewares/image_thumbnail.rb:23:in `call'
dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
rack (1.6.5) lib/rack/lock.rb:17:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
railties (4.2.6) lib/rails/engine.rb:518:in `call'
railties (4.2.6) lib/rails/application.rb:165:in `call'
rack (1.6.5) lib/rack/content_length.rb:15:in `call'
puma (3.6.2) lib/puma/configuration.rb:225:in `call'
puma (3.6.2) lib/puma/server.rb:578:in `handle_request'
puma (3.6.2) lib/puma/server.rb:415:in `process_client'
puma (3.6.2) lib/puma/server.rb:275:in `block in run'
puma (3.6.2) lib/puma/thread_pool.rb:116:in `call'
puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

I get this error when trying to execute inline js inside a liquid template to send a email:

```
                {% action "send an email like a boss" %}
                    var emailSettings = getProp('site').metafields.email_settings;

                    sendEmail({
                        to:                   'my@email.com',
                        from:                 emailSettings.from,
                        subject:              emailSettings.subject,
                        page_handle:          'email-template',
                        smtp: {
                            address:          emailSettings.smtp_address,
                            port:             emailSettings.smtp_port,
                            user_name:        emailSettings.smtp_user_name,
                            password:         emailSettings.smtp_password,
                            authentication:   'plain',
                            enable_starttls_auto: true
                        }
                    });
                {% endaction %}
```

My metafields_schema.yml:
```
email_settings:
  label: Preferences for E-mail sending
  fields:
    smtp_address:
      type: string
      hint: ''
    smtp_port:
      type: string
      hint: ''
    smtp_user_name:
      type: string
      hint: ''
    smtp_password:
      type: string
      hint: ''
    from:
      type: string
      hint: ''
    subject:
      type: string
      hint: ''
```

My site.yml metafields:
```
metafields:
  email_settings:
    smtp_address: 'host'
    smtp_port: '25'
    smtp_user_name: 'user'
    smtp_password: 'password'
    from: 'my@mail.com'
    subject: 'subject'
```

Any ideas?

**Comment by did** [comment]
hi @loyaruarutoitsu, I don't see anything wrong in your code. In the meantime, we're upgrading duktape to a new version (https://github.com/judofyr/duktape.rb/pull/36). This newer version will return a better error message (in your case, the name of the faulty variable).
